"""Make creditor, due_date, and status optional

Revision ID: bbf0d0857a6d
Revises: dadb2a619bdb
Create Date: 2025-06-16 18:19:32.219633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbf0d0857a6d'
down_revision = 'dadb2a619bdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debts', schema=None) as batch_op:
        batch_op.alter_column('creditor',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('due_date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debts', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('due_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('creditor',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
