"""Add date to Hustle model

Revision ID: d5426697a12c
Revises: bbf0d0857a6d
Create Date: 2025-06-16 18:55:07.516634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5426697a12c'
down_revision = 'bbf0d0857a6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hustles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hustles', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
