"""Add date to Debt

Revision ID: dadb2a619bdb
Revises: fc9b18f392c0
Create Date: 2025-06-16 17:52:29.454362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dadb2a619bdb'
down_revision = 'fc9b18f392c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debts', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
