"""Add description to Debt

Revision ID: fc9b18f392c0
Revises: a4923fefad2d
Create Date: 2025-06-16 17:49:16.661422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc9b18f392c0'
down_revision = 'a4923fefad2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debts', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
